baseURL = 'https://shaiiong.com/'
languageCode = 'en-us'
title = 'Shaii Ong'
theme = "starter-garden"

[params]
author = "Shaii Ong"
dateFormat = "02 Jan, 2006"
logo = "flower.svg"
[[params.garden.content_types.notes]]
icon = "â—"
image = "content-type-notes.png"
title = "Notes"
subtitle = "A spell for"
description = "Quick thoughts & ideas"
link = "/garden/notes"
[[params.garden.content_types.experiments]]
icon = "â–²"
image = "content-type-experiments.png"
title = "Experiments"
subtitle = "A spell for"
description = "More structured writing"
link = "/garden/experiments"
[[params.garden.content_types.pins]]
icon = "â˜…"
image = "content-type-pins.png"
title = "Pins"
subtitle = "A spell for"
description = "Bookmarked links"
link = "/garden/pins"
[[params.garden.content_types.portraits]]
icon = "âœš"
image = "content-type-portraits.png"
title = "Portraits"
subtitle = "A spell for"
description = "Illustrated self portraits"
link = "/garden/portraits"
[[params.garden.content_types.projects]]
icon = "â¬Ÿ"
image = "content-type-projects.png"
title = "Projects"
subtitle = "A spell for"
description = "Portfolio of work"
link = "/garden/projects"

[params.callouts]
default = "ğŸ„"
tip = "ğŸƒ"
info = "â„¹ï¸"
warning = "âš ï¸"
danger = "â›”ï¸"
link = "ğŸ”—"

[params.pins.status]
using = "Have tried and can recommend"
exploring = "Looks cool, haven't tried"

# Table of contents
[markup]
[markup.tableOfContents]
endLevel = 2
ordered = false
startLevel = 2
[markup.goldmark]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.highlight]
style = "gruvbox"
wrapperClass = "snippet"


[frontmatter]
lastmod = ["date_tended", ":git", "date", ":default"]

[taxonomies]
tag = "tags"
category = "categories"
growth_stage = "growth_stage"
connects_to = "connects_to"
builds_on = "builds_on"
challenges = "challenges"
# Epistemic Status
certainty = "certainty"
evidence = "evidence"
# Maintenance Status
freshness = "freshness"
completeness = "completeness"
# Thematic Clustering
mindset = "mindset"
domain = "domain"

[menus]
[[menus.main]]
name = 'Garden'
identifier = 'garden'
pageRef = '/garden'
weight = 20

# Temporarily disable menu until I figure it out properly
# [[menus.main]]
# name = 'Notes'
# parent = 'garden'
# pageRef = '/notes'
# weight = 21

# [[menus.main]]
# name = 'Experiments'
# parent = 'garden'
# pageRef = '/experiments'
# weight = 22

# [[menus.main]]
# name = 'Pins'
# parent = 'garden'
# pageRef = '/pins'
# weight = 23

# [[menus.main]]
# name = 'Portraits'
# parent = 'garden'
# pageRef = '/portraits'
# weight = 24

# [[menus.main]]
# name = 'Projects'
# parent = 'garden'
# pageRef = '/projects'
# weight = 25

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30
